version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
sphinx:
  configuration: Docs/conf.py

formats:
  - pdf
  - htmlzip

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: Docs/requirements.txt

     
