
 -- Filter OSM entities to keep only roads
DROP TABLE IF EXISTS MAP_ROADS;
CREATE TABLE MAP_ROADS(ID_WAY BIGINT PRIMARY KEY,HIGHWAY_TYPE varchar(30) ) AS SELECT DISTINCT ID_WAY, VALUE HIGHWAY_TYPE FROM MAP_WAY_TAG WT, MAP_TAG T
WHERE WT.ID_TAG = T.ID_TAG AND T.TAG_KEY IN ('highway');
DROP TABLE IF EXISTS MAP_ROADS_GEOM;
-- Make roads lines and convert coordinates from angle to meter
-- EPSG 32630 is UTM 30-N http://spatialreference.org/ref/epsg/wgs-84-utm-zone-30n/
CREATE TABLE MAP_ROADS_GEOM AS SELECT ID_WAY, st_updatez(ST_precisionreducer(ST_SIMPLIFYPRESERVETOPOLOGY(ST_TRANSFORM(ST_SETSRID(ST_MAKELINE(THE_GEOM), 4326), 2154),0.1),1), 0.05) THE_GEOM, HIGHWAY_TYPE T FROM (SELECT (SELECT
ST_ACCUM(THE_GEOM) THE_GEOM FROM (SELECT N.ID_NODE, N.THE_GEOM,WN.ID_WAY IDWAY FROM MAP_NODE
N,MAP_WAY_NODE WN WHERE N.ID_NODE = WN.ID_NODE ORDER BY WN.NODE_ORDER) WHERE  IDWAY = W.ID_WAY)
THE_GEOM ,W.ID_WAY, B.HIGHWAY_TYPE FROM MAP_WAY W,MAP_ROADS B WHERE W.ID_WAY = B.ID_WAY) GEOM_TABLE;
DROP TABLE MAP_ROADS;

-- Build fake traffic using only road category
DROP TABLE IF EXISTS ROADS;
CREATE TABLE ROADS(ID SERIAL,ID_WAY long , THE_GEOM LINESTRING, CLAS_ADM int, AADF int) AS
SELECT null, ID_WAY, THE_GEOM,
CASEWHEN(T = 'trunk', 21,
CASEWHEN(T = 'primary', 41,
CASEWHEN(T = 'secondary', 41,
CASEWHEN(T = 'tertiary',41, 57)))) CLAS_ADM,

CASEWHEN(T = 'trunk', 47000,
CASEWHEN(T = 'primary', 35000,
CASEWHEN(T = 'secondary', 12000,
CASEWHEN(T = 'tertiary',7800,
CASEWHEN(T = 'residential',4000, 1600
))))) AADF FROM MAP_ROADS_GEOM where T in ('trunk', 'primary', 'secondary', 'tertiary', 'residential', 'unclassified') ;
