name: CI + Windows Installer

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: imresamu/postgis:17-3.5
        env:
          POSTGRES_USER: noisemodelling
          POSTGRES_PASSWORD: noisemodelling
          POSTGRES_DB: noisemodelling_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Build Maven
        run: mvn clean test package -B
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: noisemodelling_db
          POSTGRES_USER: noisemodelling
          POSTGRES_PASSWORD: noisemodelling

      - name: Install bsdtar
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools

      - name: Extract ZIP artifact
        run: |
          mkdir NoiseModelling
          bsdtar -xvf noisemodelling-scripts/target/*.zip --strip-components=1 -C NoiseModelling

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-linux
          path: NoiseModelling/

      - name: Upload ZIP for Windows job
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: noisemodelling-scripts/target/*.zip


  windows-installer:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set versions
        run: |
          $shortSha = "${{ github.sha }}".Substring(0,7)
          $build = "${{ github.run_number }}"
          echo "APP_VERSION=0.0.$build.0" >> $env:GITHUB_ENV
          echo "APP_VERSION_TXT=0.0.0-$build-$shortSha" >> $env:GITHUB_ENV

      - name: Download ZIP
        uses: actions/download-artifact@v4
        with:
          name: dist-zip
          path: dist

      - name: Extract ZIP
        run: |
          Expand-Archive -Path "dist\*.zip" -DestinationPath extracted -Force

      - name: Find JAR
        run: |
          $jar = Get-ChildItem -Recurse -Path extracted -Filter *.jar |
                 Sort-Object Length -Descending |
                 Select-Object -First 1
          echo "JAR_PATH=$($jar.FullName)" >> $env:GITHUB_ENV
      - name: Debug JAR
        run: |
          dir installer
          
      - name: Copy JRE for packaging
        run: |
          New-Item -ItemType Directory -Force -Path installer\jre

          Copy-Item "$env:JAVA_HOME\*" installer\jre -Recurse -Force 

      - name: Debug JRE
        run: |
          dir installer\jre
          dir installer\jre\bin    

      - name: Install Launch4j
        run: choco install launch4j --yes --no-progress

      - name: Build EXE config
        run: |
          $JAR_PATH = $env:JAR_PATH -replace '\\','/'
          (Get-Content installer\launch4j-config.xml) `
            -replace 'JAR_PLACEHOLDER', $JAR_PATH `
            -replace 'APP_VERSION_PLACEHOLDER', $env:APP_VERSION `
            -replace 'APP_VERSION_TXT_PLACEHOLDER', $env:APP_VERSION_TXT `
          | Set-Content installer\launch4j-config-final.xml


      - name: Create EXE
        run: |
          java -jar "C:\Program Files (x86)\Launch4j\launch4j.jar" installer\launch4j-config-final.xml
          
      - name: Install NSIS
        run: choco install nsis --yes --no-progress 

      - name: Build installer
        run: |
          & "C:\Program Files (x86)\NSIS\makensis.exe" /DAPP_VERSION=$env:APP_VERSION installer\installer.nsi

      - name: Debug installer
        run: |
          dir installer
          
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: installer\NoiseModelling-${{ env.APP_VERSION }}-Setup.exe
        
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            $HOME/.m2/
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      # Checkout the source code of the project
      - name: Checkout
        uses: actions/checkout@v4
      # Setup the jdk using version 11 of Adoptium Temurin
      - name: Setup java 11 using Adoptium Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Building
        run: mvn test install javadoc:test-javadoc javadoc:jar package -B
      - name: Extract packaged zip with windows
        run: |
          unzip -o noisemodelling-scripts/target/*.zip -d NoiseModelling
      - name: Find extracted folder (PowerShell)
        id: folder
        shell: pwsh
        run: |
          $subdir = Get-ChildItem -Path NoiseModelling -Directory | Select-Object -First 1
          echo "folder=$($subdir.FullName)" >> $env:GITHUB_OUTPUT
      - name: Run tutorial script
        run: |
          bin\ScriptRunner -w ./ -s scripts/Import_and_Export/Import_File.groovy --pathFile resources/ground_type.shp
        working-directory: ${{ steps.folder.outputs.folder }}
